import { SquawkCase, Vendor, VendorMemoryStat, ActivityLog, HistoricalLearningResponse } from './types';

export const MOCK_CASES: SquawkCase[] = [
  {
    id: "CASE-SQK-2048",
    tail_number: "VT-SQK",
    aircraft_type: "Boeing 737-800",
    defect_description: "Engine vibration reported during climb. Crew observed abnormal vibration indication. Hydraulic System A EDP low pressure warning.",
    ata_chapter: "29 - Hydraulic Power / 72 - Engine",
    part_number: "HP-2048",
    part_name: "Engine-Driven Hydraulic Pump Assembly (EDP)",
    priority: "AOG",
    location: "DEL Terminal 3 MRO Hangar",
    airport: "DEL",
    operator: "Air Indigo Wings",
    flight_number: "SQ-204",
    defect_category: "Hydraulic System / EDP",
    severity: "AOG_CRITICAL",
    urgency: "URGENT_UNDER_4H",
    reported_symptoms: "Abnormal engine vibration on flight deck and hydraulic System A EDP low pressure alert.",
    operational_impact: "Aircraft grounded at DEL T3 MRO Hangar. Scheduled flight SQ-205 to BOM held.",
    mel_cdl_info: "MEL 29-11-01 Non-deferrable for CAT III operations",
    required_maintenance_team: "Hydraulic Line Specialist",
    reporter_name: "Capt. R. Sharma (Air Indigo Wings)",
    reporter_contact: "ops.del@indigoair.in | +91 11 4963 8000",
    current_stage: "HUMAN_REVIEW",
    confidence_score: 0.96,
    risk_level: "LOW",
    status: "Awaiting Approval",
    estimated_recovery_hours: 8.33,
    deadline_hours: 18.0,
    max_acceptable_cost: 25000.0,
    carbon_kg: 420.0,
    replan_count: 0,
    is_malformed: false,
    is_demo: true,
    demo_key: "hero_sqk2048",
    demo_badge: "FLAGSHIP HERO AOG",
    vakh_submission_id: "vakh_sub_sqk2048_del",
    vakh_record_url: "https://vakh.com",
    vakh_form_id: "vakh_form_aog_intake_v1",
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    active_plan: {
      supplier_id: "VEND-AEROPARTS",
      supplier_name: "AeroParts Inc. (Singapore)",
      part_id: "PART-HP2048-AERO",
      part_number: "HP-2048",
      condition: "Factory New",
      quantity_available: 2,
      part_cost: 14900.0,
      freight_cost: 3300.0,
      total_landed_cost: 18200.0,
      total_eta_hours: 8.33,
      carrier: "Singapore Cargo Express (Flight SQ-402)",
      origin: "SIN",
      destination: "DEL",
      route_description: "Changi (SIN) -> Indira Gandhi Intl (DEL) -> Direct Hangar 4 Transfer",
      carbon_kg: 420.0,
      reliability_score: 0.96,
      compliance_status: "PASS",
      compliance_pass: true,
      compliance_notes: "Dual Release (FAA 8130-3 + EASA Form 1) with complete OEM birth certificate.",
      recovery_score: 92.4,
      is_feasible: true,
      rank: 1,
      is_recommended: true
    },
    scoring_weights: { delivery: 0.40, reliability: 0.25, cost: 0.15, compliance: 0.10, carbon: 0.10 },
    candidates: [
      {
        id: "CAND-C1-01",
        case_id: "CASE-SQK-2048",
        vendor_id: "VEND-AEROPARTS",
        part_id: "PART-HP2048-AERO",
        vendor_name: "AeroParts Inc. (Singapore)",
        part_number: "HP-2048",
        condition: "Factory New",
        part_cost: 14900.0,
        freight_cost: 3300.0,
        total_landed_cost: 18200.0,
        estimated_eta_hours: 8.33,
        shipping_method: "Singapore Cargo Express (Flight SQ-402)",
        documentation_status: "PASS",
        doc_notes: "Dual Release (FAA 8130-3 + EASA Form 1) with complete OEM birth certificate.",
        vendor_reliability_score: 0.96,
        overall_rank: 1,
        is_recommended: true,
        is_flagged: false,
        confidence: 0.96
      },
      {
        id: "CAND-C1-02",
        case_id: "CASE-SQK-2048",
        vendor_id: "VEND-SKYSUPPLY",
        part_id: "PART-HP2048-SKY",
        vendor_name: "SkySupply Global (Mumbai Hub)",
        part_number: "HP-2048",
        condition: "Overhauled",
        part_cost: 12900.0,
        freight_cost: 1800.0,
        total_landed_cost: 14700.0,
        estimated_eta_hours: 11.17,
        shipping_method: "Air India Cargo (Flight AI-608)",
        documentation_status: "PASS",
        doc_notes: "FAA Form 8130-3 Overhauled tag with authorized 121 trace.",
        vendor_reliability_score: 0.91,
        overall_rank: 2,
        is_recommended: false,
        is_flagged: false,
        confidence: 0.91
      },
      {
        id: "CAND-C1-03",
        case_id: "CASE-SQK-2048",
        vendor_id: "VEND-GLOBAL",
        part_id: "PART-HP2048-GLOB",
        vendor_name: "GlobalParts Aviation GmbH",
        part_number: "HP-2048",
        condition: "Serviceable",
        part_cost: 5000.0,
        freight_cost: 4200.0,
        total_landed_cost: 9200.0,
        estimated_eta_hours: 20.5,
        shipping_method: "Lufthansa Cargo (Flight LH-760)",
        documentation_status: "FAIL",
        doc_notes: "DEADLINE_EXCEEDED: ETA of 20.5h exceeds max allowable window of 18.0h.",
        vendor_reliability_score: 0.84,
        overall_rank: 3,
        is_recommended: false,
        is_flagged: true,
        flag_reason: "DEADLINE_EXCEEDED: 20.5h ETA misses 18.0h deadline by +2.5h.",
        confidence: 0.20
      }
    ],
    agent_results: [],
    recovery_actions: [],
    recovery_actions_list: [
      { id: "act-1", step_number: 1, title: "Assign hydraulic maintenance technician", description: "Dispatch certified A&P hydraulic lead to DEL T3 Hangar 4.", assigned_role: "Hydraulic Lead Specialist", status: "Completed", updated_at: "2026-09-27T16:05:00Z" },
      { id: "act-2", step_number: 2, title: "Inspect affected hydraulic system", description: "Conduct borescope and visual leak check on EDP pump assembly.", assigned_role: "Lead Inspector", status: "In Progress", updated_at: "2026-09-27T16:15:00Z" },
      { id: "act-3", step_number: 3, title: "Identify leaking component", description: "Isolate high-pressure discharge port seal and shaft housing.", assigned_role: "A&P Technician", status: "Pending", updated_at: "2026-09-27T16:00:00Z" },
      { id: "act-4", step_number: 4, title: "Check required replacement component", description: "Verify part HP-2048 dual airworthiness certification (8130-3/EASA Form 1).", assigned_role: "Materials / QC Inspector", status: "Pending", updated_at: "2026-09-27T16:00:00Z" },
      { id: "act-5", step_number: 5, title: "Replace component if approved", description: "Torque pump to AMM 29-11-00 specifications with calibrated tooling.", assigned_role: "Lead Mechanic", status: "Pending", updated_at: "2026-09-27T16:00:00Z" },
      { id: "act-6", step_number: 6, title: "Perform required inspection/testing", description: "Run hydraulic system A ground test cart at 3,000 PSI; verify no pressure drop.", assigned_role: "Avionics / Systems Tech", status: "Pending", updated_at: "2026-09-27T16:00:00Z" },
      { id: "act-7", step_number: 7, title: "Verify aircraft readiness", description: "Perform full flight deck BITE test; clear master caution annunciator.", assigned_role: "Duty Maintenance Manager", status: "Pending", updated_at: "2026-09-27T16:00:00Z" },
      { id: "act-8", step_number: 8, title: "Release aircraft according to authorized procedures", description: "Sign CRS (Certificate of Release to Service) and return VT-SQK to line ops.", assigned_role: "Chief Inspector / Signatory", status: "Pending", updated_at: "2026-09-27T16:00:00Z" }
    ],
    recovery_updates: [
      { id: "upd-sqk-01", case_id: "CASE-SQK-2048", source: "VAKH_INTAKE", author: "Capt. R. Sharma", message: "AOG reported via Vakh structured intake. Abnormal engine vibration & hydraulic A EDP low pressure warning.", status: "ACTIVE", vakh_sync_status: "SYNCED", created_at: "2026-09-27T16:01:00Z" },
      { id: "upd-sqk-02", case_id: "CASE-SQK-2048", source: "SQUAWK_AI", author: "SQUAWK Recovery Orchestrator", message: "Multi-agent AI evaluated 3 global suppliers. Selected AeroParts SIN (Flight SQ-402, ETA 8h 20m, Dual 8130-3/EASA Form 1).", status: "ACTIVE", vakh_sync_status: "SYNCED", created_at: "2026-09-27T16:02:44Z" },
      { id: "upd-sqk-03", case_id: "CASE-SQK-2048", source: "TECHNICIAN", author: "K. Nair (A&P Lead)", message: "Technician team reached aircraft at DEL Hangar 4. Borescope inspection confirms EDP shaft seal weeping.", status: "ACTIVE", vakh_sync_status: "SYNCED", created_at: "2026-09-27T16:15:00Z" }
    ]
  },
  {
    id: "CASE-ORD-4201",
    tail_number: "N42Q",
    aircraft_type: "Boeing 737-800",
    defect_description: "High Pressure Turbine (HPT) Stage 1 Nozzle thermal stress indication during post-flight borescope. Coating spallation beyond AMM limits.",
    ata_chapter: "72 - Engine / Turbine",
    part_number: "NOZ-HPT-7214",
    part_name: "HPT Stage 1 Nozzle Guide Vane Segment",
    priority: "AOG",
    location: "ORD Gate B12 Hangar",
    airport: "ORD",
    operator: "Skyline Airways",
    flight_number: "SK-420",
    defect_category: "Engine / Turbine",
    severity: "CRITICAL",
    urgency: "HIGH",
    reported_symptoms: "Borescope photo shows thermal barrier coating degradation on leading edge.",
    operational_impact: "Departure hold at terminal. Revenue flight to DEN cancelled.",
    mel_cdl_info: "MEL 72-51-02 Maintenance hold required",
    required_maintenance_team: "Lead Powerplant Inspector",
    reporter_name: "Powerplant Lead (ORD Base)",
    reporter_contact: "ord.maint@skyline.aero",
    current_stage: "SPECIALIST_ROUTING",
    confidence_score: 0.92,
    risk_level: "MEDIUM",
    status: "Processing",
    estimated_recovery_hours: 6.8,
    deadline_hours: 16.0,
    max_acceptable_cost: 30000.0,
    carbon_kg: 310.0,
    replan_count: 0,
    is_malformed: false,
    is_demo: true,
    demo_key: "ord_n42q",
    demo_badge: "PARALLEL AI SOURCING",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    active_plan: {
      supplier_id: "VEND-APEX",
      supplier_name: "Apex Rotables & Spares (DFW)",
      part_id: "PART-NOZ-APEX",
      part_number: "NOZ-HPT-7214",
      condition: "Factory New",
      quantity_available: 4,
      part_cost: 18500.0,
      freight_cost: 2900.0,
      total_landed_cost: 21400.0,
      total_eta_hours: 6.8,
      carrier: "FedEx Priority Aviation Cargo (Flight FX-142)",
      origin: "DFW",
      destination: "ORD",
      route_description: "DFW Alliance Cargo -> Chicago O'Hare Direct Line Ramp",
      carbon_kg: 310.0,
      reliability_score: 0.93,
      compliance_status: "PASS",
      compliance_pass: true,
      recovery_score: 94.1,
      is_recommended: true
    },
    candidates: [
      {
        id: "CAND-C2-01",
        case_id: "CASE-ORD-4201",
        vendor_id: "VEND-APEX",
        part_id: "PART-NOZ-APEX",
        vendor_name: "Apex Rotables & Spares (DFW)",
        part_number: "NOZ-HPT-7214",
        condition: "Factory New",
        part_cost: 18500.0,
        freight_cost: 2900.0,
        total_landed_cost: 21400.0,
        estimated_eta_hours: 6.8,
        shipping_method: "FedEx Priority Aviation Cargo (FX-142)",
        documentation_status: "PASS",
        doc_notes: "FAA 8130-3 + EASA Form 1 Dual Release.",
        vendor_reliability_score: 0.93,
        overall_rank: 1,
        is_recommended: true,
        is_flagged: false,
        confidence: 0.93
      },
      {
        id: "CAND-C2-02",
        case_id: "CASE-ORD-4201",
        vendor_id: "VEND-AEROPARTS",
        part_id: "PART-NOZ-AERO",
        vendor_name: "AeroParts Inc. (Singapore)",
        part_number: "NOZ-HPT-7214",
        condition: "Overhauled",
        part_cost: 16200.0,
        freight_cost: 5800.0,
        total_landed_cost: 22000.0,
        estimated_eta_hours: 14.5,
        shipping_method: "Singapore Cargo (SQ-12)",
        documentation_status: "PASS",
        doc_notes: "Dual Release tags verified.",
        vendor_reliability_score: 0.96,
        overall_rank: 2,
        is_recommended: false,
        is_flagged: false,
        confidence: 0.88
      }
    ],
    agent_results: [],
    recovery_actions: []
  },
  {
    id: "CASE-DFW-1802",
    tail_number: "N18AX",
    aircraft_type: "Airbus A320-200",
    defect_description: "TCAS Processor failure (ATA 34). In-flight collision avoidance degraded. Direct replacement required prior to revenue release.",
    ata_chapter: "34 - Navigation / TCAS",
    part_number: "RAD-TCAS-3444",
    part_name: "TCAS II Directional Antenna Processor",
    priority: "AOG",
    location: "DFW Terminal E Gate 18",
    airport: "DFW",
    operator: "TransGlobal Express",
    flight_number: "TG-180",
    defect_category: "Navigation / TCAS",
    severity: "HIGH",
    urgency: "HIGH",
    reported_symptoms: "BITE code TCAS FAIL annunciated on captain's PFD.",
    operational_impact: "Departure hold at terminal.",
    mel_cdl_info: "MEL 34-43-01 No Go without TCAS II operational",
    required_maintenance_team: "Avionics Fast-Response",
    reporter_name: "First Officer M. Vance",
    current_stage: "HUMAN_REVIEW",
    confidence_score: 0.94,
    risk_level: "LOW",
    status: "Awaiting Approval",
    estimated_recovery_hours: 5.5,
    deadline_hours: 14.0,
    max_acceptable_cost: 15000.0,
    carbon_kg: 180.0,
    replan_count: 0,
    is_malformed: false,
    is_demo: true,
    demo_key: "dfw_n18ax",
    demo_badge: "AVIONICS FAST-TRACK",
    created_at: new Date(Date.now() - 10800000).toISOString(),
    updated_at: new Date().toISOString(),
    active_plan: {
      supplier_id: "VEND-APEX",
      supplier_name: "Apex Rotables & Spares (DFW Local)",
      part_id: "PART-TCAS-APEX",
      part_number: "RAD-TCAS-3444",
      condition: "Factory New",
      quantity_available: 2,
      part_cost: 8400.0,
      freight_cost: 1800.0,
      total_landed_cost: 10200.0,
      total_eta_hours: 5.5,
      carrier: "Local DFW Airside Dedicated Courier",
      origin: "DFW",
      destination: "DFW",
      route_description: "DFW Alliance Warehouse -> Terminal E Gate 18 Airside Transfer",
      carbon_kg: 45.0,
      reliability_score: 0.93,
      compliance_status: "PASS",
      compliance_pass: true,
      recovery_score: 96.2,
      is_recommended: true
    },
    candidates: [
      {
        id: "CAND-C3-01",
        case_id: "CASE-DFW-1802",
        vendor_id: "VEND-APEX",
        part_id: "PART-TCAS-APEX",
        vendor_name: "Apex Rotables & Spares (DFW)",
        part_number: "RAD-TCAS-3444",
        condition: "Factory New",
        part_cost: 8400.0,
        freight_cost: 1800.0,
        total_landed_cost: 10200.0,
        estimated_eta_hours: 5.5,
        shipping_method: "DFW Dedicated Airside Van",
        documentation_status: "PASS",
        doc_notes: "FAA Form 8130-3 Factory New tag with OEM trace.",
        vendor_reliability_score: 0.93,
        overall_rank: 1,
        is_recommended: true,
        is_flagged: false,
        confidence: 0.94
      }
    ],
    agent_results: [],
    recovery_actions: []
  },
  {
    id: "CASE-LAX-7203",
    tail_number: "N72LK",
    aircraft_type: "Boeing 777-300ER",
    defect_description: "Right engine Integrated Drive Generator (IDG) thermal disconnect and oil pressure loss (ATA 24). Generator offline.",
    ata_chapter: "24 - Electrical Power",
    part_number: "GEN-IDG-2401",
    part_name: "Integrated Drive Generator 90kVA",
    priority: "AOG",
    location: "LAX Maintenance Hangar 5",
    airport: "LAX",
    operator: "Pacific Horizon",
    flight_number: "PH-720",
    defect_category: "Electrical Power",
    severity: "CRITICAL",
    urgency: "HIGH",
    reported_symptoms: "IDG OIL LO PRESS caution light illuminated on overhead panel.",
    operational_impact: "Flight PH-721 to HND grounded at LAX.",
    mel_cdl_info: "MEL 24-11-01 Non-deferrable for ETOPS flights",
    required_maintenance_team: "Base Heavy Electrical",
    reporter_name: "Capt. E. Lindqvist",
    current_stage: "APPROVED",
    confidence_score: 0.91,
    risk_level: "LOW",
    status: "Approved & Dispatched",
    estimated_recovery_hours: 12.0,
    deadline_hours: 24.0,
    max_acceptable_cost: 55000.0,
    carbon_kg: 520.0,
    replan_count: 0,
    is_malformed: false,
    is_demo: true,
    demo_key: "lax_n72lk",
    demo_badge: "DISPATCHED ROTABLE",
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date().toISOString(),
    active_plan: {
      supplier_id: "VEND-JETC",
      supplier_name: "JetComponent Express (LAX Local)",
      part_id: "PART-GEN-JETC",
      part_number: "GEN-IDG-2401",
      condition: "Overhauled",
      quantity_available: 1,
      part_cost: 38500.0,
      freight_cost: 4000.0,
      total_landed_cost: 42500.0,
      total_eta_hours: 12.0,
      carrier: "JetComponent Priority Logistics Van",
      origin: "LAX",
      destination: "LAX",
      route_description: "LAX Imperial Cargo -> Hangar 5 Dedicated Delivery",
      carbon_kg: 60.0,
      reliability_score: 0.86,
      compliance_status: "PASS",
      compliance_pass: true,
      recovery_score: 90.8,
      is_recommended: true
    },
    candidates: [
      {
        id: "CAND-C4-01",
        case_id: "CASE-LAX-7203",
        vendor_id: "VEND-JETC",
        part_id: "PART-GEN-JETC",
        vendor_name: "JetComponent Express (LAX)",
        part_number: "GEN-IDG-2401",
        condition: "Overhauled",
        part_cost: 38500.0,
        freight_cost: 4000.0,
        total_landed_cost: 42500.0,
        estimated_eta_hours: 12.0,
        shipping_method: "JetComponent Hotshot Van",
        documentation_status: "PASS",
        doc_notes: "Dual release with OEM rewind certificate.",
        vendor_reliability_score: 0.86,
        overall_rank: 1,
        is_recommended: true,
        is_flagged: false,
        confidence: 0.91
      }
    ],
    agent_results: [],
    recovery_actions: []
  },
  {
    id: "CASE-JFK-3105",
    tail_number: "N311VA",
    aircraft_type: "Airbus A321neo",
    defect_description: "Environmental Control System (ECS) Pack 1 Air Cycle Machine turbine bearing friction warning (ATA 21). System isolated.",
    ata_chapter: "21 - Air Conditioning / ECS",
    part_number: "ACM-ECS-2109",
    part_name: "Air Cycle Machine Pack Assembly",
    priority: "AOG",
    location: "JFK Terminal 4 Line Station",
    airport: "JFK",
    operator: "CoastAir",
    flight_number: "CA-311",
    defect_category: "Environmental Control System (ECS)",
    severity: "AOG_CRITICAL",
    urgency: "STANDARD_UNDER_12H",
    current_stage: "COMPLETED",
    confidence_score: 0.98,
    risk_level: "LOW",
    status: "Resolved",
    estimated_recovery_hours: 7.2,
    deadline_hours: 20.0,
    max_acceptable_cost: 22000.0,
    carbon_kg: 290.0,
    replan_count: 0,
    is_malformed: false,
    is_demo: true,
    demo_key: "jfk_n311va",
    demo_badge: "RESOLVED & VERIFIED",
    vakh_submission_id: "vakh_sub_jfk3105_ca",
    vakh_record_url: "https://vakh.com",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    resolved_at: new Date(Date.now() - 72000000).toISOString(),
    updated_at: new Date().toISOString(),
    candidates: [],
    agent_results: [],
    recovery_actions: [],
    resolution: {
      id: "res-jfk-3105",
      case_id: "CASE-JFK-3105",
      actual_resolution: "Replaced ACM Pack Assembly with overhauled unit from GlobalParts Aviation. Conducted ground pneumatic run-up test at 45 PSI; turbine bearing temp stable within normal parameters.",
      actual_recovery_time_hours: 6.8,
      parts_used: ["ACM-ECS-2109 (SN-ACM-9104)"],
      root_cause: "Fatigue bearing degradation in Stage 1 turbine rotor causing intermittent friction trips.",
      delay_minutes: 75,
      maintenance_team: "JFK Terminal 4 Line Station Rapid Response Crew",
      lessons_learned: "Air Cycle Machine bearing vibration warning precedes catastrophic seizure by ~12 flight cycles. Recommend fleet-wide borescope check on A321neo batch.",
      vakh_resolution_id: "vakh_res_jfk3105",
      resolved_by: "Lead Inspector A. Kowalski (A&P-559102)",
      created_at: new Date(Date.now() - 72000000).toISOString()
    }
  },
  {
    id: "CASE-HIST-1038",
    tail_number: "VT-SQK",
    aircraft_type: "Boeing 737-800",
    defect_description: "Hydraulic System B reservoir low level alert on taxi-in. Visible fluid seepage at return manifold.",
    ata_chapter: "29 - Hydraulic Power",
    part_number: "SK-737-HYD-04",
    part_name: "Hydraulic System Return Coupling Seal Kit",
    priority: "AOG",
    location: "DEL Terminal 3 Bay 14",
    airport: "DEL",
    operator: "Air Indigo Wings",
    flight_number: "SQ-108",
    defect_category: "Hydraulic System / Return Valve",
    severity: "AOG_CRITICAL",
    urgency: "URGENT_UNDER_4H",
    current_stage: "COMPLETED",
    confidence_score: 0.97,
    risk_level: "LOW",
    status: "Resolved",
    estimated_recovery_hours: 3.5,
    deadline_hours: 6.0,
    max_acceptable_cost: 5000.0,
    carbon_kg: 45.0,
    replan_count: 0,
    is_malformed: false,
    is_demo: false,
    demo_key: "hist_sqk1038",
    demo_badge: "HISTORICAL ARCHIVE",
    vakh_submission_id: "vakh_sub_hist1038_del",
    vakh_record_url: "https://vakh.com",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    resolved_at: new Date(Date.now() - 160000000).toISOString(),
    updated_at: new Date().toISOString(),
    candidates: [],
    agent_results: [],
    recovery_actions: [],
    resolution: {
      id: "res-hist-1038",
      case_id: "CASE-HIST-1038",
      actual_resolution: "Replaced high-pressure return coupling O-rings with seal kit SK-737-HYD-04 from DEL line stores. Ground pressurization test to 3,000 PSI showed zero seepage. Cleared for line service.",
      actual_recovery_time_hours: 3.2,
      parts_used: ["SK-737-HYD-04 (Lot L-8812)"],
      root_cause: "Thermal degradation of elastomeric seal after 1,400 flight cycles in high ambient temperature operation.",
      delay_minutes: 45,
      maintenance_team: "DEL Line Maintenance Rapid Response Team 2",
      lessons_learned: "High summer ramp temperatures at DEL accelerate seal hardening on System B return manifold. Added mandatory 600-cycle inspection to airline maintenance program (AMP).",
      vakh_resolution_id: "vakh_res_hist1038",
      resolved_by: "Chief Inspector M. Chawla (A&P-440192)",
      created_at: new Date(Date.now() - 160000000).toISOString()
    }
  }
];

export const MOCK_VENDORS: Vendor[] = [
  {
    id: "VEND-AEROPARTS",
    name: "AeroParts Inc. (Singapore)",
    location_hub: "SIN",
    cage_code: "1K489",
    base_rating: 0.96,
    verified_orders_count: 28,
    on_time_deliveries: 27,
    avg_delay_minutes: 18.0,
    doc_issues_count: 0,
    calculated_reliability: 0.96,
    contact_email: "aog.sin@aeroparts.aero",
    contact_aog_desk: "+65 6788 0100"
  },
  {
    id: "VEND-SKYSUPPLY",
    name: "SkySupply Global (Mumbai Hub)",
    location_hub: "BOM",
    cage_code: "9X102",
    base_rating: 0.91,
    verified_orders_count: 24,
    on_time_deliveries: 22,
    avg_delay_minutes: 35.0,
    doc_issues_count: 1,
    calculated_reliability: 0.91,
    contact_email: "desk.bom@skysupply.aero",
    contact_aog_desk: "+91 22 6688 0400"
  },
  {
    id: "VEND-GLOBAL",
    name: "GlobalParts Aviation GmbH",
    location_hub: "FRA",
    cage_code: "7G231",
    base_rating: 0.84,
    verified_orders_count: 18,
    on_time_deliveries: 15,
    avg_delay_minutes: 120.0,
    doc_issues_count: 2,
    calculated_reliability: 0.84,
    contact_email: "aog@globalparts.de",
    contact_aog_desk: "+49 69 555-0810"
  },
  {
    id: "VEND-APEX",
    name: "Apex Rotables & Spares",
    location_hub: "DFW",
    cage_code: "3C994",
    base_rating: 0.93,
    verified_orders_count: 22,
    on_time_deliveries: 21,
    avg_delay_minutes: 25.0,
    doc_issues_count: 0,
    calculated_reliability: 0.93,
    contact_email: "priority@apexrotables.com",
    contact_aog_desk: "+1 (972) 555-APEX"
  },
  {
    id: "VEND-JETC",
    name: "JetComponent Express",
    location_hub: "LAX",
    cage_code: "4M551",
    base_rating: 0.86,
    verified_orders_count: 14,
    on_time_deliveries: 12,
    avg_delay_minutes: 55.0,
    doc_issues_count: 1,
    calculated_reliability: 0.86,
    contact_email: "orders@jetcomponent.com",
    contact_aog_desk: "+1 (310) 555-JETC"
  }
];

export const MOCK_MEMORY: {
  total_tracked_vendors: number;
  total_verified_outcomes: number;
  overall_system_reliability: number;
  vendor_stats: VendorMemoryStat[];
} = {
  total_tracked_vendors: 5,
  total_verified_outcomes: 106,
  overall_system_reliability: 0.92,
  vendor_stats: [
    { vendor_id: "VEND-AEROPARTS", vendor_name: "AeroParts Inc. (Singapore)", hub: "SIN", orders: 28, on_time_rate: 0.96, avg_delay_min: 18.0, doc_defects: 0, reliability_pct: 96.0 },
    { vendor_id: "VEND-APEX", vendor_name: "Apex Rotables & Spares", hub: "DFW", orders: 22, on_time_rate: 0.95, avg_delay_min: 25.0, doc_defects: 0, reliability_pct: 93.0 },
    { vendor_id: "VEND-SKYSUPPLY", vendor_name: "SkySupply Global (Mumbai Hub)", hub: "BOM", orders: 24, on_time_rate: 0.91, avg_delay_min: 35.0, doc_defects: 1, reliability_pct: 91.0 },
    { vendor_id: "VEND-JETC", vendor_name: "JetComponent Express", hub: "LAX", orders: 14, on_time_rate: 0.85, avg_delay_min: 55.0, doc_defects: 1, reliability_pct: 86.0 },
    { vendor_id: "VEND-GLOBAL", vendor_name: "GlobalParts Aviation GmbH", hub: "FRA", orders: 18, on_time_rate: 0.83, avg_delay_min: 120.0, doc_defects: 2, reliability_pct: 84.0 }
  ]
};

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: "act-log-01",
    case_id: "CASE-SQK-2048",
    timestamp: new Date(Date.now() - 900000).toISOString(),
    category: "PIPELINE",
    title: "AOG Incident Ingested & Classified",
    details: "VT-SQK (Boeing 737-800) logged at DEL Terminal 3. Defect: Engine vibration and Hydraulic A EDP low pressure warning."
  },
  {
    id: "act-log-02",
    case_id: "CASE-SQK-2048",
    timestamp: new Date(Date.now() - 750000).toISOString(),
    category: "SPECIALIST",
    title: "Parallel Sourcing Wave Completed",
    details: "Inventory search queried DEL, BOM, SIN, FRA. Identified 3 candidate rotables for HP-2048."
  },
  {
    id: "act-log-03",
    case_id: "CASE-SQK-2048",
    timestamp: new Date(Date.now() - 600000).toISOString(),
    category: "VALIDATOR",
    title: "Regulatory Compliance Audit Passed",
    details: "AeroParts Inc. candidate verified with dual release (FAA Form 8130-3 + EASA Form 1). 7/7 constraints satisfied."
  },
  {
    id: "act-log-04",
    case_id: "CASE-LAX-7203",
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    category: "APPROVAL",
    title: "Recovery Plan Approved & Dispatched (N72LK)",
    details: "Authorized by Tech Ops Duty Controller (License A&P-774120). Shipment courier dispatched to LAX Hangar 5."
  },
  {
    id: "act-log-05",
    case_id: "CASE-JFK-3105",
    timestamp: new Date(Date.now() - 72000000).toISOString(),
    category: "OUTCOME",
    title: "Incident Resolved: N311VA Returned to Line",
    details: "Air Cycle Machine replacement completed and verified. Aircraft released for revenue flight CA-312."
  }
];
